#pragma checksum "..\..\..\UserControls\UCAppointment.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "49278D4BA8897E7AD903178EC558263072AFA6F9"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DevExpress.Core;
using DevExpress.Mvvm;
using DevExpress.Mvvm.UI;
using DevExpress.Mvvm.UI.Interactivity;
using DevExpress.Mvvm.UI.ModuleInjection;
using DevExpress.Xpf.Core;
using DevExpress.Xpf.Core.ConditionalFormatting;
using DevExpress.Xpf.Core.DataSources;
using DevExpress.Xpf.Core.Serialization;
using DevExpress.Xpf.Core.ServerMode;
using DevExpress.Xpf.DXBinding;
using DevExpress.Xpf.Editors;
using DevExpress.Xpf.Editors.DataPager;
using DevExpress.Xpf.Editors.DateNavigator;
using DevExpress.Xpf.Editors.ExpressionEditor;
using DevExpress.Xpf.Editors.Filtering;
using DevExpress.Xpf.Editors.Flyout;
using DevExpress.Xpf.Editors.Popups;
using DevExpress.Xpf.Editors.Popups.Calendar;
using DevExpress.Xpf.Editors.RangeControl;
using DevExpress.Xpf.Editors.Settings;
using DevExpress.Xpf.Editors.Settings.Extension;
using DevExpress.Xpf.Editors.Validation;
using DevExpress.Xpf.Grid;
using DevExpress.Xpf.Grid.ConditionalFormatting;
using DevExpress.Xpf.Grid.LookUp;
using DevExpress.Xpf.Grid.TreeList;
using DevExpress.Xpf.LayoutControl;
using DevExpress.Xpf.Scheduling;
using DevExpress.Xpf.Scheduling.Common;
using DevExpress.Xpf.Scheduling.Editors;
using DevExpress.Xpf.Scheduling.Panels;
using DevExpress.Xpf.Scheduling.Themes;
using DevExpress.Xpf.Scheduling.Visual;
using ICPartners.DAL;
using ICPartners.DevxUI;
using ICPartners.DevxUI.UserControls;
using ICPartners.DevxUI.ViewModels;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace ICPartners.DevxUI.UserControls {
    
    
    /// <summary>
    /// UCAppointment
    /// </summary>
    public partial class UCAppointment : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 153 "..\..\..\UserControls\UCAppointment.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Scheduling.SchedulerControl MainScheduler;
        
        #line default
        #line hidden
        
        
        #line 158 "..\..\..\UserControls\UCAppointment.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Scheduling.AppointmentItem Customers;
        
        #line default
        #line hidden
        
        
        #line 175 "..\..\..\UserControls\UCAppointment.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Scheduling.DataSource fefe;
        
        #line default
        #line hidden
        
        
        #line 223 "..\..\..\UserControls\UCAppointment.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Scheduling.DayView dayView1;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/ICPartners.DevxUI;component/usercontrols/ucappointment.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\UserControls\UCAppointment.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 21 "..\..\..\UserControls\UCAppointment.xaml"
            ((ICPartners.DevxUI.UserControls.UCAppointment)(target)).Initialized += new System.EventHandler(this.UserControl_Initialized);
            
            #line default
            #line hidden
            return;
            case 2:
            this.MainScheduler = ((DevExpress.Xpf.Scheduling.SchedulerControl)(target));
            
            #line 153 "..\..\..\UserControls\UCAppointment.xaml"
            this.MainScheduler.SizeChanged += new System.Windows.SizeChangedEventHandler(this.MainScheduler_SizeChanged);
            
            #line default
            #line hidden
            
            #line 153 "..\..\..\UserControls\UCAppointment.xaml"
            this.MainScheduler.AppointmentWindowShowing += new DevExpress.Xpf.Scheduling.AppointmentWindowShowingEventHandler(this.MainScheduler_AppointmentWindowShowing);
            
            #line default
            #line hidden
            
            #line 153 "..\..\..\UserControls\UCAppointment.xaml"
            this.MainScheduler.ItemPropertyChanged += new DevExpress.Xpf.Scheduling.ItemPropertyChangedEventHandler(this.MainScheduler_ItemPropertyChanged);
            
            #line default
            #line hidden
            
            #line 153 "..\..\..\UserControls\UCAppointment.xaml"
            this.MainScheduler.InitNewAppointment += new DevExpress.Xpf.Scheduling.AppointmentItemEventHandler(this.MainScheduler_InitNewAppointment);
            
            #line default
            #line hidden
            
            #line 153 "..\..\..\UserControls\UCAppointment.xaml"
            this.MainScheduler.BeforeAppointmentItemDelete += new DevExpress.Xpf.Scheduling.AppointmentItemCancelEventHandler(this.SchedulerControl_BeforeAppointmentItemDelete);
            
            #line default
            #line hidden
            
            #line 153 "..\..\..\UserControls\UCAppointment.xaml"
            this.MainScheduler.AppointmentDrop += new DevExpress.Xpf.Scheduling.AppointmentItemDragDropEventHandler(this.MainScheduler_AppointmentDrop);
            
            #line default
            #line hidden
            
            #line 153 "..\..\..\UserControls\UCAppointment.xaml"
            this.MainScheduler.AppointmentsUpdated += new System.EventHandler(this.MainScheduler_AppointmentsUpdated);
            
            #line default
            #line hidden
            
            #line 153 "..\..\..\UserControls\UCAppointment.xaml"
            this.MainScheduler.ItemsCollectionChanged += new DevExpress.Xpf.Scheduling.ItemsCollectionChangedEventHandler(this.MainScheduler_ItemsCollectionChanged);
            
            #line default
            #line hidden
            
            #line 153 "..\..\..\UserControls\UCAppointment.xaml"
            this.MainScheduler.MouseDoubleClick += new System.Windows.Input.MouseButtonEventHandler(this.MainScheduler_MouseDoubleClick);
            
            #line default
            #line hidden
            return;
            case 3:
            this.Customers = ((DevExpress.Xpf.Scheduling.AppointmentItem)(target));
            return;
            case 4:
            this.fefe = ((DevExpress.Xpf.Scheduling.DataSource)(target));
            return;
            case 5:
            this.dayView1 = ((DevExpress.Xpf.Scheduling.DayView)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

