// <auto-generated />
namespace ICPartners.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class App_Job_Nav_propTest : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(App_Job_Nav_propTest));
        
        string IMigrationMetadata.Id
        {
            get { return "201809291712142_App_Job_Nav_propTest"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
