// <auto-generated />
namespace ICPartners.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class job_restored : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(job_restored));
        
        string IMigrationMetadata.Id
        {
            get { return "201807311621576_job_restored"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
