// <auto-generated />
namespace ICPartners.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class resourcerefid_replaced : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(resourcerefid_replaced));
        
        string IMigrationMetadata.Id
        {
            get { return "201810062020533_resourcerefid_replaced"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
