#pragma checksum "..\..\..\UserControls\UCCustomerSelector.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "10472E6CF91A9D1284D30668D1450DF413858B7E"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DevExpress.Core;
using DevExpress.Xpf.Core;
using DevExpress.Xpf.Core.ConditionalFormatting;
using DevExpress.Xpf.Core.DataSources;
using DevExpress.Xpf.Core.Serialization;
using DevExpress.Xpf.Core.ServerMode;
using DevExpress.Xpf.DXBinding;
using DevExpress.Xpf.Editors;
using DevExpress.Xpf.Editors.DataPager;
using DevExpress.Xpf.Editors.DateNavigator;
using DevExpress.Xpf.Editors.ExpressionEditor;
using DevExpress.Xpf.Editors.Filtering;
using DevExpress.Xpf.Editors.Flyout;
using DevExpress.Xpf.Editors.Popups;
using DevExpress.Xpf.Editors.Popups.Calendar;
using DevExpress.Xpf.Editors.RangeControl;
using DevExpress.Xpf.Editors.Settings;
using DevExpress.Xpf.Editors.Settings.Extension;
using DevExpress.Xpf.Editors.Validation;
using DevExpress.Xpf.Grid;
using DevExpress.Xpf.Grid.ConditionalFormatting;
using DevExpress.Xpf.Grid.LookUp;
using DevExpress.Xpf.Grid.TreeList;
using ICPartners.DAL;
using ICPartners.DevxUI.UserControls;
using ICPartners.DevxUI.ViewModels;
using ICPartners.Logic.Customer;
using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace ICPartners.DevxUI.UserControls
{


    /// <summary>
    /// UCCustomerSelector
    /// </summary>
    public partial class UCCustomerSelector : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector
    {

#line default
#line hidden


#line 26 "..\..\..\UserControls\UCCustomerSelector.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid CustomerMainGrid;

#line default
#line hidden


#line 34 "..\..\..\UserControls\UCCustomerSelector.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Editors.ComboBoxEdit CustomerList;

#line default
#line hidden


#line 46 "..\..\..\UserControls\UCCustomerSelector.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid CustomerDetailGrid;

#line default
#line hidden


#line 57 "..\..\..\UserControls\UCCustomerSelector.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid CustomerNameGrid;

#line default
#line hidden


#line 63 "..\..\..\UserControls\UCCustomerSelector.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Editors.ComboBoxEdit CustomerTitle;

#line default
#line hidden


#line 65 "..\..\..\UserControls\UCCustomerSelector.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Editors.TextEdit CustomerName;

#line default
#line hidden


#line 66 "..\..\..\UserControls\UCCustomerSelector.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Editors.TextEdit CustomerSurname;

#line default
#line hidden


#line 68 "..\..\..\UserControls\UCCustomerSelector.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Editors.TextEdit CustomerPhone;

#line default
#line hidden


#line 69 "..\..\..\UserControls\UCCustomerSelector.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Editors.TextEdit CustomerEMail;

#line default
#line hidden


#line 70 "..\..\..\UserControls\UCCustomerSelector.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Editors.TextEdit CustomerAddress;

#line default
#line hidden


#line 71 "..\..\..\UserControls\UCCustomerSelector.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Editors.TextEdit CustomerCity;

#line default
#line hidden

        private bool _contentLoaded;

        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent()
        {
            if (_contentLoaded)
            {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/ICPartners.DevxUI;component/usercontrols/uccustomerselector.xaml", System.UriKind.Relative);

#line 1 "..\..\..\UserControls\UCCustomerSelector.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);

#line default
#line hidden
        }

        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target)
        {
            switch (connectionId)
            {
                case 1:
                    this.Root = ((ICPartners.DevxUI.UserControls.UCCustomerSelector)(target));
                    return;
                case 2:
                    this.CustomerMainGrid = ((System.Windows.Controls.Grid)(target));
                    return;
                case 3:
                    this.CustomerList = ((DevExpress.Xpf.Editors.ComboBoxEdit)(target));

#line 34 "..\..\..\UserControls\UCCustomerSelector.xaml"
                    this.CustomerList.SelectedIndexChanged += new System.Windows.RoutedEventHandler(this.CustomerList_SelectedIndexChanged);

#line default
#line hidden

#line 34 "..\..\..\UserControls\UCCustomerSelector.xaml"
                    this.CustomerList.ProcessNewValue += new DevExpress.Xpf.Editors.ProcessNewValueEventHandler(this.CustomerList_ProcessNewValue);

#line default
#line hidden
                    return;
                case 4:
                    this.CustomerDetailGrid = ((System.Windows.Controls.Grid)(target));
                    return;
                case 5:
                    this.CustomerNameGrid = ((System.Windows.Controls.Grid)(target));
                    return;
                case 6:
                    this.CustomerTitle = ((DevExpress.Xpf.Editors.ComboBoxEdit)(target));
                    return;
                case 7:
                    this.CustomerName = ((DevExpress.Xpf.Editors.TextEdit)(target));
                    return;
                case 8:
                    this.CustomerSurname = ((DevExpress.Xpf.Editors.TextEdit)(target));
                    return;
                case 9:
                    this.CustomerPhone = ((DevExpress.Xpf.Editors.TextEdit)(target));
                    return;
                case 10:
                    this.CustomerEMail = ((DevExpress.Xpf.Editors.TextEdit)(target));
                    return;
                case 11:
                    this.CustomerAddress = ((DevExpress.Xpf.Editors.TextEdit)(target));
                    return;
                case 12:
                    this.CustomerCity = ((DevExpress.Xpf.Editors.TextEdit)(target));
                    return;
            }
            this._contentLoaded = true;
        }
    }
}

