#pragma checksum "..\..\CustomAppointmentWindow1.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "E5AA48969B0F494A80BC3C655670367C79EC7B47"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DevExpress.Mvvm;
using DevExpress.Mvvm.UI;
using DevExpress.Mvvm.UI.Interactivity;
using DevExpress.Mvvm.UI.ModuleInjection;
using DevExpress.Xpf.Bars;
using DevExpress.Xpf.DXBinding;
using DevExpress.Xpf.Editors;
using DevExpress.Xpf.Editors.DataPager;
using DevExpress.Xpf.Editors.DateNavigator;
using DevExpress.Xpf.Editors.ExpressionEditor;
using DevExpress.Xpf.Editors.Filtering;
using DevExpress.Xpf.Editors.Flyout;
using DevExpress.Xpf.Editors.Popups;
using DevExpress.Xpf.Editors.Popups.Calendar;
using DevExpress.Xpf.Editors.RangeControl;
using DevExpress.Xpf.Editors.Settings;
using DevExpress.Xpf.Editors.Settings.Extension;
using DevExpress.Xpf.Editors.Validation;
using DevExpress.Xpf.LayoutControl;
using DevExpress.Xpf.Ribbon;
using DevExpress.Xpf.Scheduling;
using DevExpress.Xpf.Scheduling.Common;
using DevExpress.Xpf.Scheduling.Editors;
using DevExpress.Xpf.Scheduling.Themes;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace ICPartners.DevxUI {
    
    
    /// <summary>
    /// CustomAppointmentWindow1
    /// </summary>
    public partial class CustomAppointmentWindow1 : DevExpress.Xpf.Ribbon.DXRibbonWindow, System.Windows.Markup.IComponentConnector {
        
        
        #line 15 "..\..\CustomAppointmentWindow1.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal ICPartners.DevxUI.CustomAppointmentWindow1 window;
        
        #line default
        #line hidden
        
        
        #line 25 "..\..\CustomAppointmentWindow1.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Bars.BarButtonItem toolbar_barItemSave;
        
        #line default
        #line hidden
        
        
        #line 26 "..\..\CustomAppointmentWindow1.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Bars.BarButtonItem toolbar_barItemPrevious;
        
        #line default
        #line hidden
        
        
        #line 27 "..\..\CustomAppointmentWindow1.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Bars.BarButtonItem toolbar_barItemNext;
        
        #line default
        #line hidden
        
        
        #line 28 "..\..\CustomAppointmentWindow1.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Bars.BarButtonItem toolbar_barItemDelete;
        
        #line default
        #line hidden
        
        
        #line 33 "..\..\CustomAppointmentWindow1.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Bars.BarButtonItem barItemSaveAndClose;
        
        #line default
        #line hidden
        
        
        #line 34 "..\..\CustomAppointmentWindow1.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Bars.BarButtonItem barItemDelete;
        
        #line default
        #line hidden
        
        
        #line 37 "..\..\CustomAppointmentWindow1.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Bars.BarEditItem barItemLabel;
        
        #line default
        #line hidden
        
        
        #line 38 "..\..\CustomAppointmentWindow1.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Bars.BarEditItem barItemStatus;
        
        #line default
        #line hidden
        
        
        #line 39 "..\..\CustomAppointmentWindow1.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Bars.BarEditItem barItemResources;
        
        #line default
        #line hidden
        
        
        #line 40 "..\..\CustomAppointmentWindow1.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Bars.BarEditItem barItemResource;
        
        #line default
        #line hidden
        
        
        #line 41 "..\..\CustomAppointmentWindow1.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Bars.BarEditItem barItemReminder;
        
        #line default
        #line hidden
        
        
        #line 47 "..\..\CustomAppointmentWindow1.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.LayoutControl.LayoutControl validationContainer;
        
        #line default
        #line hidden
        
        
        #line 48 "..\..\CustomAppointmentWindow1.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid appgrid;
        
        #line default
        #line hidden
        
        
        #line 65 "..\..\CustomAppointmentWindow1.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel spmainservice;
        
        #line default
        #line hidden
        
        
        #line 67 "..\..\CustomAppointmentWindow1.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel spsubservices;
        
        #line default
        #line hidden
        
        
        #line 76 "..\..\CustomAppointmentWindow1.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Editors.TextEdit editorSubject;
        
        #line default
        #line hidden
        
        
        #line 83 "..\..\CustomAppointmentWindow1.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Editors.TextEdit editorLocation;
        
        #line default
        #line hidden
        
        
        #line 85 "..\..\CustomAppointmentWindow1.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.LayoutControl.LayoutItem layoutStartTime;
        
        #line default
        #line hidden
        
        
        #line 87 "..\..\CustomAppointmentWindow1.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Editors.DateEdit editorStartDate;
        
        #line default
        #line hidden
        
        
        #line 88 "..\..\CustomAppointmentWindow1.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Editors.TextEdit editorStartTime;
        
        #line default
        #line hidden
        
        
        #line 89 "..\..\CustomAppointmentWindow1.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Editors.CheckEdit editorAllDay;
        
        #line default
        #line hidden
        
        
        #line 94 "..\..\CustomAppointmentWindow1.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Editors.TextEdit editorDescription;
        
        #line default
        #line hidden
        
        
        #line 97 "..\..\CustomAppointmentWindow1.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal DevExpress.Xpf.Editors.TextEdit editorhistory;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/ICPartners.DevxUI;component/customappointmentwindow1.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\CustomAppointmentWindow1.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.window = ((ICPartners.DevxUI.CustomAppointmentWindow1)(target));
            
            #line 15 "..\..\CustomAppointmentWindow1.xaml"
            this.window.Loaded += new System.Windows.RoutedEventHandler(this.window_Loaded);
            
            #line default
            #line hidden
            
            #line 15 "..\..\CustomAppointmentWindow1.xaml"
            this.window.Closing += new System.ComponentModel.CancelEventHandler(this.window_Closing);
            
            #line default
            #line hidden
            return;
            case 2:
            this.toolbar_barItemSave = ((DevExpress.Xpf.Bars.BarButtonItem)(target));
            return;
            case 3:
            this.toolbar_barItemPrevious = ((DevExpress.Xpf.Bars.BarButtonItem)(target));
            return;
            case 4:
            this.toolbar_barItemNext = ((DevExpress.Xpf.Bars.BarButtonItem)(target));
            return;
            case 5:
            this.toolbar_barItemDelete = ((DevExpress.Xpf.Bars.BarButtonItem)(target));
            return;
            case 6:
            this.barItemSaveAndClose = ((DevExpress.Xpf.Bars.BarButtonItem)(target));
            
            #line 33 "..\..\CustomAppointmentWindow1.xaml"
            this.barItemSaveAndClose.TouchDown += new System.EventHandler<System.Windows.Input.TouchEventArgs>(this.barItemSaveAndClose_TouchDown);
            
            #line default
            #line hidden
            
            #line 33 "..\..\CustomAppointmentWindow1.xaml"
            this.barItemSaveAndClose.TouchEnter += new System.EventHandler<System.Windows.Input.TouchEventArgs>(this.barItemSaveAndClose_TouchEnter);
            
            #line default
            #line hidden
            return;
            case 7:
            this.barItemDelete = ((DevExpress.Xpf.Bars.BarButtonItem)(target));
            return;
            case 8:
            this.barItemLabel = ((DevExpress.Xpf.Bars.BarEditItem)(target));
            return;
            case 9:
            this.barItemStatus = ((DevExpress.Xpf.Bars.BarEditItem)(target));
            return;
            case 10:
            this.barItemResources = ((DevExpress.Xpf.Bars.BarEditItem)(target));
            return;
            case 11:
            this.barItemResource = ((DevExpress.Xpf.Bars.BarEditItem)(target));
            return;
            case 12:
            this.barItemReminder = ((DevExpress.Xpf.Bars.BarEditItem)(target));
            return;
            case 13:
            this.validationContainer = ((DevExpress.Xpf.LayoutControl.LayoutControl)(target));
            return;
            case 14:
            this.appgrid = ((System.Windows.Controls.Grid)(target));
            return;
            case 15:
            this.spmainservice = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 16:
            this.spsubservices = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 17:
            this.editorSubject = ((DevExpress.Xpf.Editors.TextEdit)(target));
            return;
            case 18:
            this.editorLocation = ((DevExpress.Xpf.Editors.TextEdit)(target));
            return;
            case 19:
            this.layoutStartTime = ((DevExpress.Xpf.LayoutControl.LayoutItem)(target));
            return;
            case 20:
            this.editorStartDate = ((DevExpress.Xpf.Editors.DateEdit)(target));
            return;
            case 21:
            this.editorStartTime = ((DevExpress.Xpf.Editors.TextEdit)(target));
            return;
            case 22:
            this.editorAllDay = ((DevExpress.Xpf.Editors.CheckEdit)(target));
            return;
            case 23:
            this.editorDescription = ((DevExpress.Xpf.Editors.TextEdit)(target));
            return;
            case 24:
            this.editorhistory = ((DevExpress.Xpf.Editors.TextEdit)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

